import type { GroupWithDetails } from "@/lib/types/groups"

// Mock groups data for preview
export const mockGroups: GroupWithDetails[] = [
  {
    id: "1",
    name: "Downtown Savings Circle",
    description:
      "A vibrant community of young professionals pooling resources for emergency funds and investment opportunities.",
    logo: "/savings-group-logo.jpg",
    privacy: "PUBLIC",
    status: "ACTIVE",
    contributionAmount: 50000,
    contributionFrequency: "MONTHLY",
    depositGoal: 5000000,
    interestRate: 5.5,
    maxMembers: 20,
    memberCount: 15,
    requireApproval: false,
    createdAt: new Date("2024-01-15"),
    adminName: "Sarah Mwansa",
    adminEmail: "sarah.mwansa@downtown-circle.zm",
    adminPhone: "+260 97 123 4567",
    groupRules:
      "1. Monthly contributions due by the 5th of each month\n2. Three consecutive missed payments result in suspension\n3. Members must attend at least 75% of quarterly meetings\n4. Loan requests require 7 days notice\n5. Respectful communication is mandatory",
    bylaws:
      "Members agree to contribute ZMW 50,000 monthly. Emergency withdrawals allowed with 48-hour notice and 5% fee. Loan approval requires 60% member vote. Interest earned is distributed quarterly based on contribution consistency.",
  },
  {
    id: "2",
    name: "Women Entrepreneurs Fund",
    description: "Supporting female business owners through collective savings and micro-loans.",
    logo: "/diverse-women-entrepreneurs.png",
    privacy: "PRIVATE",
    status: "ACTIVE",
    contributionAmount: 75000,
    contributionFrequency: "MONTHLY",
    depositGoal: 10000000,
    interestRate: 6.0,
    maxMembers: 25,
    memberCount: 18,
    requireApproval: true,
    createdAt: new Date("2024-02-01"),
    adminName: "Grace Phiri",
    adminEmail: "grace@womenentrepreneurs.zm",
    adminPhone: "+260 96 234 5678",
    groupRules:
      "1. Open to female entrepreneurs only\n2. Business registration proof required\n3. Monthly contributions of ZMW 75,000 mandatory\n4. Mentorship participation encouraged\n5. Late fees: ZMW 5,000 per week after grace period",
    bylaws:
      "This fund supports women-owned businesses through savings and loans. Members receive business development training quarterly. Loan amounts up to 3x total contributions. Repayment terms: 6-12 months with 6% annual interest.",
  },
  {
    id: "3",
    name: "Tech Workers Savings",
    description: "High-earning tech professionals building wealth together through disciplined monthly contributions.",
    logo: "/tech-savings.jpg",
    privacy: "INVITE_ONLY",
    status: "ACTIVE",
    contributionAmount: 150000,
    contributionFrequency: "MONTHLY",
    depositGoal: 20000000,
    interestRate: 7.5,
    maxMembers: 15,
    memberCount: 12,
    requireApproval: true,
    createdAt: new Date("2024-01-20"),
    adminName: "Joseph Banda",
    adminEmail: "joseph.banda@techsavings.zm",
    adminPhone: "+260 95 345 6789",
    groupRules:
      "1. Employment in tech industry verified\n2. Minimum income threshold: ZMW 15,000/month\n3. Auto-debit enrollment required\n4. Investment strategy reviews quarterly\n5. Confidentiality of member information maintained",
    bylaws:
      "High-contribution group for tech professionals. Monthly ZMW 150,000 contributions invested in diversified portfolio. Members share in investment gains. Early exit penalty: 10% of balance. Annual strategy meeting mandatory.",
  },
  {
    id: "4",
    name: "Market Vendors Association",
    description: "Local market traders supporting each other with weekly contributions and emergency loans.",
    logo: "/market-vendors.jpg",
    privacy: "PUBLIC",
    status: "ACTIVE",
    contributionAmount: 25000,
    contributionFrequency: "WEEKLY",
    depositGoal: 3000000,
    interestRate: 4.0,
    maxMembers: 30,
    memberCount: 28,
    requireApproval: false,
    createdAt: new Date("2023-11-10"),
    adminName: "Martha Zulu",
    adminEmail: "martha@marketvendors.zm",
    adminPhone: "+260 97 456 7890",
    groupRules:
      "1. Weekly ZMW 25,000 contributions every Friday\n2. Market stall ownership or lease required\n3. Emergency loans available same-day for members in good standing\n4. Group meetings every Sunday after market hours\n5. Two-week notice required for planned absences",
    bylaws:
      "Supporting market vendors with accessible savings. Weekly contributions build emergency fund. Small loans (up to ZMW 500,000) approved within 24 hours. 4% monthly interest on loans. Solidarity is our strength.",
  },
  {
    id: "5",
    name: "University Staff Cooperative",
    description: "Academic and administrative staff building a sustainable savings culture for major life goals.",
    logo: "/university-staff.jpg",
    privacy: "PRIVATE",
    status: "ACTIVE",
    contributionAmount: 100000,
    contributionFrequency: "MONTHLY",
    depositGoal: 15000000,
    interestRate: 5.0,
    maxMembers: 40,
    memberCount: 35,
    requireApproval: true,
    createdAt: new Date("2023-09-01"),
    adminName: "Dr. Peter Tembo",
    adminEmail: "p.tembo@university.zm",
    adminPhone: "+260 96 567 8901",
    groupRules:
      "1. Current university employment required\n2. Payroll deduction for contributions\n3. Educational development projects prioritized\n4. Semi-annual dividend distribution\n5. Retirement planning workshops provided",
    bylaws:
      "University staff cooperative focused on long-term wealth building. Monthly ZMW 100,000 via payroll deduction. Loans for education, housing, medical emergencies. Maximum loan: ZMW 5,000,000. Repayment: up to 24 months.",
  },
  {
    id: "6",
    name: "Young Parents Circle",
    description: "New parents saving together for education, healthcare, and family emergencies.",
    logo: "/young-parents.jpg",
    privacy: "PUBLIC",
    status: "ACTIVE",
    contributionAmount: 40000,
    contributionFrequency: "BI_WEEKLY",
    depositGoal: 8000000,
    interestRate: 4.5,
    maxMembers: 25,
    memberCount: 20,
    requireApproval: false,
    createdAt: new Date("2024-03-15"),
    adminName: "Patricia Kaluba",
    adminEmail: "patricia@youngparents.zm",
    adminPhone: "+260 97 678 9012",
    groupRules:
      "1. Parent or guardian of children under 10 years\n2. Bi-weekly ZMW 40,000 contributions\n3. Child-related expenses prioritized for loans\n4. Parenting workshops monthly\n5. Family emergencies receive expedited support",
    bylaws:
      "Supporting young families through collective savings. Bi-weekly contributions build education fund. Emergency loans for medical/school needs. Educational savings accounts for children. Community over competition.",
  },
  {
    id: "7",
    name: "Church Community Fund",
    description: "Faith-based savings group supporting members through life's challenges and celebrations.",
    logo: "/church-community.png",
    privacy: "INVITE_ONLY",
    status: "ACTIVE",
    contributionAmount: 60000,
    contributionFrequency: "MONTHLY",
    depositGoal: 12000000,
    interestRate: 3.5,
    maxMembers: 50,
    memberCount: 45,
    requireApproval: true,
    createdAt: new Date("2023-06-01"),
    adminName: "Rev. Michael Mulenga",
    adminEmail: "rev.michael@churchfund.zm",
    adminPhone: "+260 95 789 0123",
    groupRules:
      "1. Active church membership required\n2. Monthly ZMW 60,000 contributions\n3. Prayer meeting attendance encouraged\n4. Benevolence requests reviewed monthly\n5. Christian values guide all decisions",
    bylaws:
      "Faith-based community savings supporting members spiritually and financially. Interest-free emergency loans up to ZMW 1,000,000. Benevolence fund for members in crisis. Accountability partners assigned. Stewardship and generosity emphasized.",
  },
  {
    id: "8",
    name: "Freelancers Alliance",
    description: "Independent workers creating financial stability through consistent group savings.",
    logo: "/freelancers.jpg",
    privacy: "PUBLIC",
    status: "ACTIVE",
    contributionAmount: 80000,
    contributionFrequency: "MONTHLY",
    depositGoal: 10000000,
    interestRate: 6.5,
    maxMembers: 20,
    memberCount: 14,
    requireApproval: false,
    createdAt: new Date("2024-02-20"),
    adminName: "Daniel Moyo",
    adminEmail: "daniel@freelancers.zm",
    adminPhone: "+260 96 890 1234",
    groupRules:
      "1. Self-employed or freelance income verification\n2. Monthly ZMW 80,000 contributions\n3. Income smoothing loans during slow months\n4. Skill-sharing sessions quarterly\n5. Late payment grace period: 5 days",
    bylaws:
      "Supporting independent workers with flexible savings. Monthly contributions build stability fund. Short-term loans for cash flow gaps. Tax planning resources provided. Network of freelancers supporting each other.",
  },
]
